name = "APTFunctorFactorization"
defaultTargets = ["APTFunctorFactorization"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0-rc2"

[[lean_lib]]
name = "APTFunctorFactorization"
roots = ["APTFunctorFactorization"]
