"""Domain model for the APT vNext deterministic reducer proposal."""

from .commands import CanonicalCommandEnvelope, CommandSchemaError
from .events import EventEnvelope, EventSchemaError, EventType, GuardResult, payload_hash
from .effect_runtime import (
    BudgetDecision,
    BudgetLimit,
    EffectExecutionGrant,
    ExecutionOutcome,
    ReconciliationOutcome,
    ResourceAccess,
    ResourceClaim,
    RuntimeBudget,
    RuntimeContractError,
    RuntimeUsage,
    detect_stuck,
    evaluate_budget,
    progress_signature,
)
from .state_codec import STATE_CODEC_VERSION, StateCodecError, decode_state, encode_state
from .state import (
    AptCycleState,
    ArtifactRecord,
    AssuranceStatus,
    CycleLifecycle,
    EffectLifecycle,
    EffectAttemptOutcome,
    EffectAttemptRecord,
    EffectState,
    GenerationHistory,
    RealizationStatus,
    SemanticMaturity,
    WorkItemKind,
    WorkItemLifecycle,
    WorkItemState,
    state_hash,
)

__all__ = [
    "AptCycleState",
    "ArtifactRecord",
    "AssuranceStatus",
    "CanonicalCommandEnvelope",
    "CommandSchemaError",
    "CycleLifecycle",
    "BudgetDecision",
    "BudgetLimit",
    "EffectExecutionGrant",
    "ExecutionOutcome",
    "ReconciliationOutcome",
    "ResourceAccess",
    "ResourceClaim",
    "RuntimeBudget",
    "RuntimeContractError",
    "RuntimeUsage",
    "detect_stuck",
    "evaluate_budget",
    "progress_signature",
    "EffectAttemptOutcome",
    "EffectAttemptRecord",
    "EffectLifecycle",
    "EffectState",
    "EventEnvelope",
    "EventSchemaError",
    "EventType",
    "GenerationHistory",
    "GuardResult",
    "RealizationStatus",
    "SemanticMaturity",
    "STATE_CODEC_VERSION",
    "StateCodecError",
    "WorkItemKind",
    "WorkItemLifecycle",
    "WorkItemState",
    "decode_state",
    "encode_state",
    "payload_hash",
    "state_hash",
]
