"""Ports for the APT vNext durable runtime.

# KG: apt-tpa-legion-engine-canon-2026-06-12
# KG: APT_SCW_TDAD_canonical
"""

from .effect_queue import (
    EffectQueue,
    EffectQueueCorruption,
    EffectQueueError,
    LeaseConflict,
    LeaseNotFound,
    LeaseRecord,
    LeaseRequest,
    LeaseStatus,
    ReconciliationProbeAcquisition,
    ReconciliationProbeConclusion,
    ReconciliationProbePermit,
    ReconciliationProbePermitState,
    ResourceClaimConflict,
    ReconciliationProbeConflict,
    ReconciliationProbeExhausted,
)
from .effects import (
    Clock,
    EffectCancellationAuthorization,
    EffectCancellationVerifier,
    EffectExecutionRequest,
    EffectExecutionResult,
    EffectExecutor,
    EffectGrantVerifier,
    EffectPortSchemaError,
    EffectReconciler,
    EffectReconciliationRequest,
    EffectReconciliationResult,
    EffectResultStore,
    IdGenerator,
    StoredEffectResult,
)

from .event_store import (
    AppendResult,
    CommandIdConflict,
    CommandReceipt,
    CommandReceiptDraft,
    EventStore,
    OutboxRecord,
    PersistenceSchemaError,
    Snapshot,
    StreamBindingConflict,
    StoreConflict,
    StoreCorruption,
    StoreError,
)

__all__ = [
    "AppendResult",
    "CommandIdConflict",
    "CommandReceipt",
    "CommandReceiptDraft",
    "EventStore",
    "EffectQueue",
    "EffectQueueCorruption",
    "EffectQueueError",
    "LeaseConflict",
    "LeaseNotFound",
    "LeaseRecord",
    "LeaseRequest",
    "LeaseStatus",
    "ReconciliationProbeAcquisition",
    "ReconciliationProbeConclusion",
    "ReconciliationProbePermit",
    "ReconciliationProbePermitState",
    "ResourceClaimConflict",
    "ReconciliationProbeConflict",
    "ReconciliationProbeExhausted",
    "Clock",
    "EffectCancellationAuthorization",
    "EffectCancellationVerifier",
    "EffectExecutionRequest",
    "EffectExecutionResult",
    "EffectExecutor",
    "EffectGrantVerifier",
    "EffectPortSchemaError",
    "EffectReconciler",
    "EffectReconciliationRequest",
    "EffectReconciliationResult",
    "EffectResultStore",
    "IdGenerator",
    "StoredEffectResult",
    "OutboxRecord",
    "PersistenceSchemaError",
    "Snapshot",
    "StreamBindingConflict",
    "StoreConflict",
    "StoreCorruption",
    "StoreError",
]
